### ISSUE TITLE
About MLP_small_box_w1_fewshot.tar

### ISSUE THREAD

**Issue by BlouseDong** [Hzzone/PseCo#10]
Could you please clarify which training file trained the MLP_small_box_w1_fewshot.tar file that cls_head is loaded from? I suspect it was trained by 4_1_train_roi_head.py and saved without an extension. When I renamed it to .tar, I found that their dictionary keys are different. Therefore, I'm unsure about the role of 'cls_head-10000' and how to obtain the MLP_small_box_w1_fewshot.tar file."

**Comment by Hzzone** [comment]
It is trained by 4_1_train_roi_head.py and can be loaded through `torch.load`. I named the files with `.tar` just due to personal preferences.

**Comment by BlouseDong** [comment]
I'm sorry, but I'm still encountering issues.
Their keys are different, so I can't load it. I'm not quite sure what mistakes I made during training. I apologize for bothering you.
![微信截图_20240620112834](https://github.com/Hzzone/PseCo/assets/116430824/e00b3793-821e-47b1-84f4-4fe2d847e908)

**Comment by Hzzone** [comment]
Hi, there may be some inconsistencies because I have sometimes updated my codebase.

The first line has saved model weights and other results. You can retrieve the weights of MLP by `checkpoint['cls_head']`

**Comment by BlouseDong** [comment]
Thank you for your patient response. The issue has been resolved. I apologize for bothering you.
