### ISSUE TITLE
Threshold for Paper Performance

### ISSUE THREAD

**Issue by jwahnn** [Hzzone/PseCo#11]
What is the threshold (i.e. the confidence score for each bounding box) that you use to get the MAE and RMSE values during evaluation?

**Comment by Hzzone** [comment]
I coded a notebook and you can have a look.
The threshold on the val set is 0.36 with MAE 15.0 and MSE 67.3, a bit better than in the paper.

**Comment by jwahnn** [comment]
Are you using a different threshold for each image by any chance when moving on to the test set?

**Comment by Hzzone** [comment]
Please see the code by youself.
