### ISSUE TITLE
4_1_train_roi_head.py 部分代码不懂

### ISSUE THREAD

**Issue by lichen14** [Hzzone/PseCo#14]
https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/4_1_train_roi_head.py#L60

这里从pseudo_boxes_data_vith.pth读取的all_pseudo_boxes似乎没有['pred_boxes']和['pred_ious']的属性，所以我跑这段代码报错了。

另外，还想请教一下，L55-L61这里的for循环的意义是什么？似乎后面没有用到这里的变量了？

感谢解答

**Comment by Hzzone** [comment]
https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/3_extract_proposals.py#L194

Please try to read the code by yourself first and then ask me if you are indeed unable to understand.

**Comment by lichen14** [comment]
谢谢回复，代码我能理解一些。
我没有恶意哈，也不是挑刺～很感谢作者开源，respect这项工作，只是很想跑通代码，然后再改改哈哈

主要的问题是：我如果用您在readme里给的，在https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/4_1_train_roi_head.py#L60   这里就可以正常跑通，即pseudo_boxes_data_vith.pth读取的all_pseudo_boxes就能使用['pred_boxes']和['pred_ious']的属性。
但是我如果使用https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/1_generate_data.ipynb  的代码，不改动什么内容，save得到的pseudo_boxes_data_vith.pth，再去跑4_1_train_roi_head.py就会报错，没有['pred_boxes']和['pred_ious']的属性。
请问是1_generate_data.ipynb产生pseudo_boxes_data时是有什么漏掉了吗？

另外，还想请教一下，https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/4_1_train_roi_head.py#L69   这里的`num_masks = 5`的作用？ https://github.com/Hzzone/PseCo/issues/15#issue-2394479544

**Comment by Hzzone** [comment]
1. 代码分成 4 步，每一步的目的都很明确，pred_boxes等是在第三步 [3_extract_proposals.py](https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/3_extract_proposals.py#L194) 中提取候选框得到的。
2. num_masks 是 SAM 的单个Prompt分割结果的mask数量: whole, part, subpart etc，5 应该是选全部的作为proposal。

**Comment by lichen14** [comment]
> 1. 代码分成 4 步，每一步的目的都很明确，pred_boxes等是在第三步 [3_extract_proposals.py](https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/3_extract_proposals.py#L194) 中提取候选框得到的。
> 
>     2. num_masks 是 SAM 的单个Prompt分割结果的mask数量: whole, part, subpart etc，5 应该是选全部的作为proposal。


非常感谢回复，第2点明白了，第1点还是有些疑惑，可能是我表达的问题：
- 第三步： https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/3_extract_proposals.py#L194 这个for循环结束时保存的all_predictions_vith_0,1,2,3.pth，随后把它们都合并成all_predictions_vith.pth了
- 第四步 https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/4_1_train_roi_head.py#L48 读取了all_predictions_vith.pth 作为all_predictions变量，然后在for循环里送给target['predictions']，但是这个target变量和all_predictions变量在第四步后续就没有出现过了，所以这个for循环有什么作用呢？
- 其实我最开始想问的是，第四步中读取第一步生成的all_pseudo_boxes ： https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/4_1_train_roi_head.py#L54 （其他步骤中我没发现有保存为pseudo_boxes_data_vith.pth的内容），但是第一步保存的‘pseudo_boxes_data’是没有'pred_boxes'属性的，所以是否我有错过什么？我如果使用你在百度网盘里提供的'pseudo_boxes_data_vith'就会有'pred_boxes'属性

**Comment by lichen14** [comment]
> 1. 代码分成 4 步，每一步的目的都很明确，pred_boxes等是在第三步 [3_extract_proposals.py](https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/3_extract_proposals.py#L194) 中提取候选框得到的。
> 
>     2. num_masks 是 SAM 的单个Prompt分割结果的mask数量: whole, part, subpart etc，5 应该是选全部的作为proposal。


非常感谢回复，第2点明白了，第1点还是有些疑惑，可能是我表达的问题：
- 第三步： https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/3_extract_proposals.py#L194 这个for循环结束时保存的all_predictions_vith_0,1,2,3.pth，随后把它们都合并成all_predictions_vith.pth了
- 第四步 https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/4_1_train_roi_head.py#L48 读取了all_predictions_vith.pth 作为all_predictions变量，然后在for循环里送给target['predictions']，但是这个target变量和all_predictions变量在第四步后续就没有出现过了，所以这个for循环有什么作用呢？
- 其实我最开始想问的是，第四步中读取第一步生成的all_pseudo_boxes  https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/4_1_train_roi_head.py#L54，（其他步骤中我没发现有保存为pseudo_boxes_data_vith.pth的内容），但是第一步保存的‘pseudo_boxes_data’是没有'pred_boxes'属性的，所以是否我有错过什么？我如果使用你在百度网盘里提供的'pseudo_boxes_data_vith'就会有'pred_boxes'属性

**Comment by Hzzone** [comment]
1. all_data 是个字典，python dict的修改是inplace的，遍历之后会把prediction合并到all_data里面。
2. 生成伪标签这一步，只用到框没有用到pred iou，上传的数据有可能是我的历史代码遗留的问题。你可以在第一步把iou保存下来。如果实在不会的话，你可以把这两行：
target['annotations']['boxes'] = all_pseudo_boxes[fname]['pred_boxes']
target['annotations']['ious'] = all_pseudo_boxes[fname]['pred_ious']
修改为: 
target['annotations']['boxes'] = all_pseudo_boxes[fname]

**Comment by lichen14** [comment]
感谢答疑 :+1:

**Comment by kaigelee** [comment]
https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/4_1_train_roi_head.py#L265

请问 您懂这一步骤吗？自己和自己计算iou是什么意思？？结果不是恒为1吗 @lichen14 @Hzzone

**Comment by lichen14** [comment]
> https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/4_1_train_roi_head.py#L265
> 
> 请问 您懂这一步骤吗？自己和自己计算iou是什么意思？？结果不是恒为1吗 @lichen14 @Hzzone

@kaigelee 
抱歉，这个问题我也没注意到，无法回答。
后续没有做这方面的课题了，就没有继续深入下去。

**Comment by PREPONDERANCE** [comment]
> [PseCo/fsc147/4_1_train_roi_head.py](https://github.com/Hzzone/PseCo/blob/0192ee521cd3786ed5f2d89231fd74567ef87d9c/fsc147/4_1_train_roi_head.py#L265)
> 
> Line 265 in [0192ee5](/Hzzone/PseCo/commit/0192ee521cd3786ed5f2d89231fd74567ef87d9c)
> 
>  iou_scores = vision_ops.box_iou(region_boxes[i], region_boxes[i]) 
> 请问 您懂这一步骤吗？自己和自己计算iou是什么意思？？结果不是恒为1吗 [@lichen14](https://github.com/lichen14) [@Hzzone](https://github.com/Hzzone)

您好，我觉得这里原作者意思应该是每个 region_box 和所有的 region_boxes 做 IoU 计算，相似的 box 其对应的 CLIP 特征应该也是相似的，据此来进行知识蒸馏，所以此处应为代码错误。

**Comment by Hzzone** [comment]
region_boxes是一个 prompt 数\*mask 数\*4 的 bounding box 坐标，取对应位置就是mask 数*4，也就是一个 prompt 对应的 mask 内部算 IOU。同一个 prompt，生成的mask 的 IOU如果高于阈值应该为正样本。自己和自己肯定是正样吧，跨mask 可能也有正样本。所以这里不是代码错误。

**Comment by PREPONDERANCE** [comment]
> region_boxes是一个 prompt 数*mask 数*4 的 bounding box 坐标，取对应位置就是mask 数*4，也就是一个 prompt 对应的 mask 内部算 IOU。同一个 prompt，生成的mask 的 IOU如果高于阈值应该为正样本。自己和自己肯定是正样吧，跨mask 可能也有正样本。所以这里不是代码错误。

明白了，感谢解答！
