### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './PseCo/data/fsc147/clip_text_prompt.pth'

### ISSUE THREAD

**Issue by salcanmor** [Hzzone/PseCo#2]
Hi there, I'm running your Colab notebook but, when running:
`clip_text_prompts = torch.load(f'{project_root}/data/fsc147/clip_text_prompt.pth', map_location='cpu')`

I get this error:
**FileNotFoundError: [Errno 2] No such file or directory: './PseCo/data/fsc147/clip_text_prompt.pth'**

Any idea why I'm not having the model clip_text_prompt.pth ?

Thanks in advance

![image](https://github.com/Hzzone/PseCo/assets/2684107/d1e5635e-360d-4d82-b6d3-6da579b4c625)

**Comment by Hzzone** [comment]
Hi, do you download the datasets at the beginning of the notebook?
<img width="901" alt="image" src="https://github.com/Hzzone/PseCo/assets/19267349/5dd0d4af-791e-4a27-a202-e45409d2e9c3">

<img width="505" alt="image" src="https://github.com/Hzzone/PseCo/assets/19267349/e8c02098-1e5e-4fa9-8ef3-df0a29c27eb6">
