### ISSUE TITLE
About pseudo_boxes_data_vith.pth

### ISSUE THREAD

**Issue by XiruiTeng** [Hzzone/PseCo#20]
Hello, I appreciate your great work! When running the file 4_1_train_roi_head.py, I noticed that the code requires a file named pseudo_boxes_data_vith.pth, which I couldn't find in the previous steps. I'm wondering if the 'pred_boxes' element in this file is the same as the 'pred_boxes' in all_predictions or in segment_anything_data?

**Comment by Hzzone** [comment]
https://github.com/Hzzone/PseCo/blob/main/fsc147/1_generate_data.ipynb
Generate pseudo labels with ground-truth point prompts
