### ISSUE TITLE
Availability for Inference?

### ISSUE THREAD

**Issue by jwahnn** [Hzzone/PseCo#3]
Is there a way or guideline to use model weights for inference on custom dataset instead of training?

**Comment by Hzzone** [comment]
Please see this demo: https://colab.research.google.com/github/Hzzone/PseCo/blob/master/demo_in_the_wild.ipynb
<img width="714" alt="image" src="https://github.com/Hzzone/PseCo/assets/19267349/ca1c3fe0-2105-4074-bdc5-a504a1461f7c">

**Comment by jwahnn** [comment]
Trying to run the demo file but I don't see './PseCo/data/fsc147/checkpoints/MLP_small_box_w1_fewshot.tar'

**Comment by Hzzone** [comment]
<img width="1732" alt="image" src="https://github.com/Hzzone/PseCo/assets/19267349/2f769712-3dc3-4184-8544-a34e45f5136b">
