### ISSUE TITLE
About weight file loading failed

### ISSUE THREAD

**Issue by BlouseDong** [Hzzone/PseCo#7]
Sorry to bother you, I was fascinated by your excellent work. Try running your code, I've followed your steps to cat's weight file for the preprocessed dataset. At that time, these combined weights could not be loaded normally. Is there a problem with my cat? By the way, these files are unusually large.
![微信图片_20240516171712](https://github.com/Hzzone/PseCo/assets/116430824/4fcf828d-12fa-4576-816f-4ec9a34f3e1b)
![微信图片_20240516171816](https://github.com/Hzzone/PseCo/assets/116430824/59c5a011-a94c-479d-b2e7-ac8d84635356)

**Comment by Hzzone** [comment]
It is large because I have stored the image features and all predictions in these files for FSC147 dataset. It is the preprocessed training data, instead of the weight file. You can try the demo in the wild to avoid download these files.
I will check your issue.

**Comment by Hzzone** [comment]
I have tried downloading the files from google drive and they work well.
<img width="308" alt="image" src="https://github.com/Hzzone/PseCo/assets/19267349/14530b11-844e-4c3a-826f-f92f5419b747">
You can try these python code to download files:
```python
>>> import gdown
>>> gdown.download_folder('https://drive.google.com/drive/folders/1RwxDPiL3dcUJc14arrvJkgTpI2XSddGF')
```

**Comment by BlouseDong** [comment]
Thank you very much for your answer, I'm interested in the zero-shot handling in demo_in_the_wild.ipynb, and I'd like to ask you a few questions:
1. Are the weights you trained useless for demo_in_the_wild.ipynb? Because I tested and found that demo_in_the_wild.ipynb works well for the fsc147 dataset. You should be directly tested with SAM, CLIP and other pre-trained weights.
2. Is the imported MLP_small_box_w1_zeroshot.tar file similar to the training weight file?
3. I don't know much about the NLP field, how should I train if I only want to focus on CLIP? If I get weights, how do I use them in demo_in_the_wild.ipynb?

**Comment by Hzzone** [comment]
1 and 2: you have not caught my explanation. The large files are preprocessed training data, not the weight file. The weights are in `checkpoints`. You should read the code.
