### ISSUE TITLE
Evaluation on FSC-147

### ISSUE THREAD

**Issue by jwahnn** [Hzzone/PseCo#8]
I want to test the newly trained and slightly adjusted PseCo model on the FSC benchmark. Is there a code that you used for evaluation by chance?

**Comment by Hzzone** [comment]
https://github.com/Hzzone/PseCo/blob/bcb280ead7a977f1bbe85397fde912c777932a1d/fsc147/4_1_train_roi_head.py#L299

**Comment by jwahnn** [comment]
Apologies but you mind elaborating a little more? Do I just run the file? `python3 4_1_train_roi_head.py`

**Comment by Hzzone** [comment]
If you run `4_1_train_roi_head.py`, you will train the MLP. You may need to copy these lines for your own evaluation.

**Comment by jwahnn** [comment]
Does this mean there is no code specifically for evaluation? Do you mind shedding some light on how you evaluated on the FSC data for the paper?

**Comment by Hzzone** [comment]
> https://github.com/Hzzone/PseCo/blob/bcb280ead7a977f1bbe85397fde912c777932a1d/fsc147/4_1_train_roi_head.py#L299

please see the code.

**Comment by jwahnn** [comment]
Apologies for the continuous follow-up. The entire thing seems quite complicated at the moment.

If I have my own inference code based from your `demo_in_the_wild.ipynb` that gives me a count when I input an image along with bounding boxes, is it possible that I just calculate the MAE and MSE by comparing against the ground truth count without doing all the hassle? Seems like I would only need a few lines this way.

**Comment by Hzzone** [comment]
You can use demo_in_the_wild.ipynb to calculate the MAE and MSE though it is quite slow. You must make sure that you have set a proper threshold to filter out low-confident boxes. Please refer to [4_1_train_roi_head.py](https://github.com/Hzzone/PseCo/blob/bcb280ead7a977f1bbe85397fde912c777932a1d/fsc147/4_1_train_roi_head.py#L299). I get the threshold on val set and set it on test set. In this way, you can get the results in the paper.

**Comment by jwahnn** [comment]
Doesn't the demo allow me to set a threshold as well? In that case, is speed the only issue or is there some other difference as well? I ask specifically because my adjusted model does not align well with the file you are referring to, and adjusting your evaluation code seems more work than just performing inference, getting the predicted counts, and calculating MAE and RMSE.

**Comment by Hzzone** [comment]
for p, (xmin, ymin, xmax, ymax), c in zip(scores, pred_boxes.tolist(), COLORS * len(pred_boxes)):
    if p < 0.1:
        continue
